### ISSUE TITLE
Enhancement: Add "goal scored by player"

### ISSUE THREAD

**Issue by mabertcloud** [tuvokki/pleague#10]
It would be nice if we can add who scored a certain goal.
This way we can add a "Hall of shame" list for own goals.

**Comment by tuvokki** [comment]
Can you come up with a UI to do this?
Or maybe @bramst can take this into consideration when designing the UI

**Comment by tuvokki** [comment]
That would mean to add a lot of goal-score-buttons (4 for regular goals and 4 for own goals) maybe we have to rethink this...

**Comment by mabertcloud** [comment]
Maybe use the colored "Scored!" button.

Than you move to the next screen where you get to chose the player who scored,
Then click the player who scored.

Goal counted.

**Comment by bramst** [comment]
have a look at the latest [sketch](http://idud3e.axshare.com/#c=2)

(does not include own goals... missed that part..)
