### ISSUE TITLE
Nice to have: Add positions of players (Attacker, defence)

### ISSUE THREAD

**Issue by mabertcloud** [tuvokki/pleague#3]
as title

**Comment by bramst** [comment]
this would also  make it possible to get stats about win/lose player to player, defence to offence (player A is on defence, player B on offence of the opposing team, how many times did one win from the other?)

**Comment by bramst** [comment]
should/could be combined with team selection:
http://idud3e.axshare.com/#c=2

**Comment by tuvokki** [comment]
Done in https://github.com/tuvokki/pleague/commit/a1029804e30155213d1fcf397a9fe808ed4c41f6
